### PR TITLE
fixed unnecessary ref requests #253

### PR DESCRIPTION
**Pull request by ilyavf**
Requires can-connect PR https://github.com/canjs/can-connect/pull/248

### CODE REVIEW

**Comment by justinbmeyer** [comment]
is there a fix in `can-connect`?

**Comment by justinbmeyer** [comment]
https://github.com/canjs/can-connect/pull/248#event-946974830

**Comment by justinbmeyer** [comment]
@ilyavf are both fixes needed?  Why is this one necessary?

**Comment by ilyavf** [comment]
@justinbmeyer Two fixes?
One is on can-connect (the actual fix), and another is here in bitcentive (to populate also other properties).

**Pull request merged**
